### ISSUE TITLE
Images Not showing Up in Examples

### ISSUE THREAD

**Issue by ssolson** [MHKiT-Software/MHKiT#30] opened 2020-07-24 13:54 UTC
@rpauly18  pointed this out this morning and I have confirmed

**Comment by kmruehl** [comment] 2020-07-24 15:10
@rpauly18 @ssolson looking into it now

**Comment by kmruehl** [comment] 2020-07-24 17:25
The issue is due to the location of the images generated by Jupyter notebook examples. They are actually being saved here: https://github.com/MHKiT-Software/MHKiT/tree/master/docs/doctrees/nbsphinx, but the documentation is looking for them here: https://github.com/MHKiT-Software/MHKiT/tree/master/docs/_images. I looked into how to properly configure the Jupyter notebook image directory, but was unable to find a resolution, so for now I manually copied the files into the proper directory. I'll continue to look into this issue.

**Comment by kmruehl** [comment] 2020-07-24 19:37
I have no removed the dependency on ``nbsphinx_link``, and we are using ``nbsphinx`` to compile the jupyter notebook examples. This means that the jupyter notebook examples must be on the same directory level as `conf.py`. Right now this means manually copying the jupyter notebook examples files into the appropriate directory, instead of using the files from the submodule.

**Comment by kmruehl** [comment] 2020-07-24 20:21
This issue should be fully resolved with https://github.com/MHKiT-Software/MHKiT/commit/e2a272f74416e7a7ebb6e320acc604decd760a46, where I automated the copy/past of python and matlab example files into the appropriate directory with  `make.bat`.

**Closed** 2020-07-24 20:22 UTC
Labels: bug
